[package]
name = "gdtree"
version = "2.0.2"
edition = "2024"
authors = ["Ian Young <ian@duffrecords.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
indexmap = "2.13"
regex = "1"
